"""Bilibili cookie storage in Netscape format for yt-dlp."""

from __future__ import annotations

import json
import time
from pathlib import Path

CONFIG_DIR = Path.home() / ".config" / "streamify"
COOKIE_FILE = CONFIG_DIR / "bilibili_cookies.txt"
SESSION_FILE = CONFIG_DIR / "bilibili_session.json"

# Cookies expire in 6 months (for Netscape format; actual B站 session ~30 days)
COOKIE_EXPIRY_SECONDS = 180 * 24 * 60 * 60


def get_bilibili_cookie_path() -> Path:
    return COOKIE_FILE


def has_valid_bilibili_cookies() -> bool:
    return COOKIE_FILE.exists() and COOKIE_FILE.stat().st_size > 0


def save_bilibili_cookies(
    cookies: dict[str, str],
    refresh_token: str | None = None,
) -> Path:
    """Save cookies in Netscape format that yt-dlp can read directly."""
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)

    expires = int(time.time()) + COOKIE_EXPIRY_SECONDS
    lines = ["# Netscape HTTP Cookie File", "# Generated by Streamify", ""]

    for name, value in cookies.items():
        # domain  domain_flag  path  secure  expires  name  value
        lines.append(f".bilibili.com\tTRUE\t/\tFALSE\t{expires}\t{name}\t{value}")

    COOKIE_FILE.write_text("\n".join(lines) + "\n")

    if refresh_token:
        SESSION_FILE.write_text(json.dumps({
            "refresh_token": refresh_token,
            "saved_at": int(time.time()),
        }))

    return COOKIE_FILE


def delete_bilibili_cookies() -> None:
    COOKIE_FILE.unlink(missing_ok=True)
    SESSION_FILE.unlink(missing_ok=True)
